freeze_deps:
	@echo "Freezing dependencies..."
	@pip freeze > requirements.lock.txt
	@echo "Dependencies frozen."

install_deps:
	@echo "Installing dependencies..."
	@pip install -r requirements.txt	
	@echo "Dependencies installed."